apiVersion: v1
kind: Service
metadata:
  name: echo-server-service
  namespace: training
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    app-name: echo-server
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000
