apiVersion: v1
kind: Pod
metadata:
  name: echo-server-pod
  namespace: training
spec:
  nodeSelector:
    type: dev
  containers:
    - name: echo-server
      image: landrzejewski/echo-server:v2
      ports:
        - containerPort: 8080
          name: http
      resources:
        requests:
          memory: 64M
        limits:
          memory: 128M
