apiVersion: v1
kind: PersistentVolume
metadata:
  name: training-volume
  namespace: training
spec:
  capacity:
    storage: 10G
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp/training
